wms/forms/login.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed,FileRequired,FileField
from wtforms import Form, StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired,length

class LoginForm(FlaskForm):
    filename = FileField('Upload file', validators=[FileRequired(),FileAllowed(['zip','png','jpg'])])
    username = StringField('UserName',validators=[DataRequired()])
    password = PasswordField('Password',validators=[DataRequired(),length(8,128)])
    remember = BooleanField('Remember me')
    submit = SubmitField('log in')

wms/blueprints/home.py
from flask import Blueprint, request ,flash
from flask import render_template, redirect, url_for
from wms.forms.index import LoginForm
from flask_login import login_user, current_user, logout_user
from wms.models.admin import Admin

home_bp = Blueprint('index', __name__)


@home_bp.route('/')
def index():    
    return redirect(url_for('index.login'))


@home_bp.route('/test')
def test():
    form = LoginForm()
    return render_template('test.html', form=form)


@home_bp.route('/basic', methods=['GET', 'POST'])
def basic():
    form = LoginForm()
    if request.method == 'POST' and form.validate():
        f = form.filename.data
        username = f.filename
        print(username)
        f.save(username)
        return render_template('message.html',message= username)
    message = form.password.errors
    return render_template('message.html',message=message)


@home_bp.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    pageTitle = '登录界面'
    if request.method == 'POST' and form.validate():
        if current_user.is_authenticated:
            flash('你已经登录')
            return redirect(url_for('client.clientList'))
        username = form.userName.data
        password = form.passWord.data
        admin = Admin.query.filter(Admin.name == str(username) ).first()
        if admin:
            if username == admin.name and admin.validate_password(password):
                login_user(admin)
                flash('登录成功')
                return redirect(url_for('client.clientList'))
        else:
            flash('登录失败')
            return render_template('login.html', form = form, pageTitle =pageTitle )
    return render_template('login.html', form = form, pageTitle =pageTitle )


@home_bp.route('/logout')
def logout():
    logout_user()
    return redirect( url_for('index.login'))

wms/templates/index.html
{% extends 'base/base.html' %}

{% block title %}<title>index</title>{% endblock %}

wms/templates/login.html
{% extends 'base/base.html' %}

{% block addHead %}
<link rel="stylesheet" href="{{ url_for('static', filename='font/font-awesome-4.7.0/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='font/iconic/css/material-design-iconic-font.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/util.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='js/login.js') }}">
{% endblock %}

{% block nav %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand" href="/">Amogene</a>
    </div>
</nav>
{% endblock %}

{% block container %}
{% for message in get_flashed_messages() %}
<div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>{{ message }}</strong>
</div>
{% endfor %}
<div class="limiter">
    <div class="container-login100" style="background-image: url('static/img/bg-login.jpg');">
        <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
            <form class="login100-form validate-form" action="{{ url_for('index.login') }}" method="POST">
                {{ form.csrf_token }}
                <span class="login100-form-title p-b-49">登录</span>
                <h1>{{ mess }}</h1>

                <div class="wrap-input100 validate-input m-b-23" data-validate="请输入用户名">
                    <span class="label-input100">用户名</span>
                    <!-- <input class="input100" type="text" name="username" placeholder="请输入用户名" autocomplete="off"> -->
                    {{ form.userName(class='input100') }}
                    <span class="focus-input100" data-symbol="&#xf206;"></span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="请输入密码">
                    <span class="label-input100">密码</span>
                    <!-- <input class="input100" type="password" name="pass" placeholder="请输入密码"> -->
                    {{ form.passWord(class='input100') }}
                    <span class="focus-input100" data-symbol="&#xf190;"></span>
                </div>

                <div class="text-right p-t-8 p-b-31">
                    <a href="javascript:">忘记密码？</a>
                </div>

                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <!-- <button class="login100-form-btn">登 录</button> -->
                        <!-- <a class="login100-form-btn" href="{{ url_for('client.clientList') }}">登录</a> -->
                        {{ form.submit(class='login100-form-btn') }}
                    </div>
                </div>

                <div class="txt1 text-center p-t-54 p-b-20">
                    <span>第三方登录</span>
                </div>

                <div class="flex-c-m">
                    <a href="#" class="login100-social-item bg1">
                        <i class="fa fa-wechat"></i>
                    </a>

                    <a href="#" class="login100-social-item bg2">
                        <i class="fa fa-qq"></i>
                    </a>

                    <a href="#" class="login100-social-item bg3">
                        <i class="fa fa-weibo"></i>
                    </a>
                </div>

                <div class="flex-col-c p-t-25">
                    <a href="javascript:" class="txt2">立即注册</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

wms/templates/logout.html
{% extends 'base/base.html' %}


{% block container %}


<div class=" justify-content-center" >
    <h1>你已经退出</h1>
</div>


{% endblock %}

wms/templates/message.html
{{ message }}

wms/templates/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='bootstrap/js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/admin.js') }}"></script>

</head>

<body>
   
    <form action="{{ url_for('index.basic') }}" method="POST" enctype="multipart/form-data" >

        {{ form.csrf_token }}
        <div class='form-group'>

            <div class="btn-group" >
                {{ form.filename.label }}
                {{ form.filename }}
            </div>

            {{ form.username.label }} <br>
            {{ form.username(class='form-control') }} <br>
        </div>
        <div class='from-group'>
            {{ form.password.label }} <br>
            {{ form.password(class='form-control') }} <br>
        </div>
        <div class='form-check'>
            {{ form.remember(class='form-check-input') }} 
            {{ form.remember.label }}
        </div>

        {{ form.submit(class='btn btn-primary') }} <br>
    </form>

</body>

</html>