wms/blueprints/home.py
from flask import Blueprint, request ,flash
from flask import render_template, redirect, url_for
from wms.forms.index import LoginForm
from flask_login import login_user, current_user, logout_user
from wms.models.admin import Admin

home_bp = Blueprint('index', __name__)


@home_bp.route('/')
def index():    
    return redirect(url_for('index.login'))


@home_bp.route('/test')
def test():
    form = LoginForm()
    return render_template('test.html', form=form)


@home_bp.route('/basic', methods=['GET', 'POST'])
def basic():
    form = LoginForm()
    if request.method == 'POST' and form.validate():
        f = form.filename.data
        username = f.filename
        print(username)
        f.save(username)
        return render_template('message.html',message= username)
    message = form.password.errors
    return render_template('message.html',message=message)


@home_bp.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    pageTitle = '登录界面'
    if request.method == 'POST' and form.validate():
        if current_user.is_authenticated:
            flash('你已经登录')
            return redirect(url_for('client.clientList'))
        username = form.userName.data
        password = form.passWord.data
        admin = Admin.query.filter(Admin.name == str(username) ).first()
        if admin:
            if username == admin.name and admin.validate_password(password):
                login_user(admin)
                flash('登录成功')
                return redirect(url_for('client.clientList'))
        else:
            flash('登录失败')
            return render_template('login.html', form = form, pageTitle =pageTitle )
    return render_template('login.html', form = form, pageTitle =pageTitle )


@home_bp.route('/logout')
def logout():
    logout_user()
    return redirect( url_for('index.login'))

wms/templates/base/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}

    {% if pageTitle != '' %}
    <title>{{ pageTitle }}</title>
    {% else %}
    <title>Amogene</title>
    {% endif %}
    {% endblock %}
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <!-- <script src="{{ url_for('static', filename='bootstrap/js/jquery-3.3.1.min.js') }}"></script> -->
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <!-- <script src="{{ url_for('static', filename='bootstrap/js/popper.min.js') }}"></script> -->
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="{{ url_for('static', filename='js/admin.js') }}"></script>
    {% block addHead %}
    {% endblock %}
</head>

<body {% if firstNav != '' %} data-firstnav="{{ firstnav }}" {% endif %} {% if secondnav != '' %}
    data-secondnav="{{ secondnav }}" {% endif %}>
    {% block nav %}
    <nav class="navbar navbar-expand-md bg-dark navbar-dark" id='nav'>
        <!-- Brand -->
        <a class="navbar-brand" href="{{ url_for('index.index') }}">Amogene</a>
        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navbar links -->
        <div class="collapse navbar-collapse justify-content-between " id="collapsibleNavbar">
            <ul class="navbar-nav p-2 nav-pills">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('client.clientList') }}" id="projectnav">项目</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.userList') }}" id="usernav">管理员</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" id="mailnav">邮件</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" id="lognav">日志</a>
                </li>
            </ul>
            <ul class=" navbar-nav p-2 ">
                {% if current_user.is_authenticated %}
                    <li class=" nav-item">
                            <a class=" nav-link" href="{{ url_for('index.logout') }}">退出</a> </li>
                {% else %}
                <li class=" nav-item">
                        <a class=" nav-link" href="{{ url_for('index.login') }}">登录</a></li>
                {% endif %} 
            </ul>
        </div>
    </nav>
    {% endblock %}
    <div class=" container-fluid">
        {% block container %}
        {% endblock %}
    </div>
    {% block addFooter %}
    {% endblock %}
</body>

</html>

wms/templates/base/macros.html
{% macro pager(pagination) %}
    {% if  pagination.iter_pages(left_edge=2, left_current=2,right_current=5,right_edge=2) %}
    {% set pageList = pagination.iter_pages(left_edge=2, left_current=2,right_current=5,right_edge=2) %}
    <div class=" d-flex  justify-content-center">
        <ul class="pagination">
            <li class="page-item {% if not pagination.has_prev %} disabled {% endif %}">
                <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.prev_num ) }}">上一页</a>
            </li>
            {% for page in pageList %}
                {% if page == None %}
                <li class="page-item"><a class="page-link" href="#">...</a></li>
                {% endif %}
                {% if page != None %}
                    <li class="page-item  {% if pagination.page == page %} activate {% endif %} "><a class="page-link" href="{{ url_for(request.endpoint, page=page) }}">{{page}}</a></li>
                {% endif %}
            {% endfor %}
            <li class="page-item {% if not pagination.has_next %} disabled {% endif %}">
                <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.next_num ) }}">下一页</a>
            </li>
        </ul>
    </div>
    {% endif %}
{% endmacro %}

wms/templates/base/projectBase.html
{% extends 'base/base.html' %}


{% block container %}
<div class=" row">
    <div class=" col-1">
        <div>
            <ul class=" nav nav-pills nav-pills">
                <li class=" nav-item">
                    <a class=" nav-link" href="{{ url_for('client.clientList') }}" id="clientInfo">客户信息</a>
                </li>
                <li class=" nav-item">
                    <a class=" nav-link" href="{{ url_for('project.projectList') }}?clientId=clear"
                        id="projectInfo">项目列表</a>
                </li>
                <li class=" nav-item">
                    <a class=" nav-link" href="#" id="analysisInfo">项目信息</a>
                </li>
                <li class=" nav-item">
                    <a class=" nav-link" href="{{ url_for('samples.samplesList') }}?page=clear"
                        id="samplesInfo">样品列表</a>
                </li>
            </ul>
        </div>

    </div>

    <div class=" col-11">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}

        {% if mess %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>{{ mess }}</strong>
        </div>
        {% endif %}

        {% block rightContent %}
        {% endblock %}

    </div>
</div>

{% endblock %}

wms/templates/base/userBase.html
{% extends 'base/base.html' %}

{% block container %}
<div class=" row">
    <div class=" col-1">

        <div>
            <ul class=" nav nav-pills ">
                <li class=" nav-item">
                    <a class=" nav-link active" href="{{ url_for('user.userList') }}">管理员</a>
                </li>
                <li class=" nav-item">
                    <a class=" nav-link" href="#">修改权限</a>
                </li>
            </ul>
        </div>
    </div><!-- end col-2 -->

    <div class=" col-11">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
        
        {% if mess %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>{{ mess }}</strong>
        </div>
        {% endif %}

        {% block rightContent %}
        {% endblock %}

    </div>
</div>

{% endblock %}